trigger:
- master

pool:
  vmImage: ubuntu-latest


steps:
- task: Npm@1
  inputs:
    command: 'install'

- task: Bash@3
  displayName: Publish
  env:
    VSCE_PAT: $(VSCE_PAT)
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo ">>> Publish"
      git config user.email "cbfrank@withcb.cn"
      git config user.name "cb"
      yarn install
      npm run deploy